language: clojure
lein: lein
dist: xenial

services:
  - docker

before_install:
  - export BARGE_URL=http://52.187.164.74
  - scripts/setup_for_remote_barge.sh $BARGE_URL
  - AGENT_URL=http://52.187.164.74:8080
script: lein do clean, test
